// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smkiajmmclmmrohqditu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNta2lham1tY2xtbXJvaHFkaXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTE3ODksImV4cCI6MjA2NDA4Nzc4OX0.CHRDaw4A5Pn1wbnYBgbpQKDuXcq-2ZvF7n_1ItouPzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);